AWSTemplateFormatVersion: "2010-09-09"
Description: Persistent layer
Resources:
  Persistence:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: String
      AllowMajorVersionUpgrade: Boolean
      AutoMinorVersionUpgrade: Boolean
      AvailabilityZone: String
      BackupRetentionPeriod: String
      CharacterSetName: String
      CopyTagsToSnapshot: Boolean
      DBClusterIdentifier: String
      DBInstanceClass: String
      DBInstanceIdentifier: String
      DBName: String
      DBParameterGroupName: String
      DBSecurityGroups:
        - String
      DBSnapshotIdentifier: String
      DBSubnetGroupName: String
      DeleteAutomatedBackups: Boolean
      DeletionProtection: Boolean
      Domain: String
      DomainIAMRoleName: String
      EnableCloudwatchLogsExports:
        - String
      EnableIAMDatabaseAuthentication: Boolean
      EnablePerformanceInsights: Boolean
      Engine: String
      EngineVersion: String
      Iops: Integer
      KmsKeyId: String
      LicenseModel: String
      MasterUserPassword: String
      MasterUsername: String
      MonitoringInterval: Integer
      MonitoringRoleArn: String
      MultiAZ: Boolean
      OptionGroupName: String
      PerformanceInsightsKMSKeyId: String
      PerformanceInsightsRetentionPeriod: Integer
      Port: String
      PreferredBackupWindow: String
      PreferredMaintenanceWindow: String
      ProcessorFeatures:
        - ProcessorFeature
      PromotionTier: Integer
      PubliclyAccessible: Boolean
      SourceDBInstanceIdentifier: String
      SourceRegion: String
      StorageEncrypted: Boolean
      StorageType: String
      Tags:
        - Tag
      Timezone: String
      UseDefaultProcessorFeatures: Boolean
      VPCSecurityGroups:
        - String
