AWSTemplateFormatVersion: "2010-09-09"
Description: Persistence layer
Resources:
  Persistence:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage:
        Ref: DBAllocatedStorage
      DBInstanceClass:
        Ref: DBInstanceClass
      DBName:
        Ref: DBName
      Engine: MySQL
      EngineVersion: "5.6.13"
      MasterUserPassword:
        Ref: DBPassword
      MasterUsername:
        Ref: DBUser
      Tags:
        - Key: Name
          Value: "My SQL Database"
